version: "3.9"

services:

  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db-new
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5444:5444"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flask-app:
    build: .
    container_name: POSTGRES_AI_ANALYZER
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      GEMINI_API_KEY: 
    restart: always

volumes:
  pgdata: